version: '3.1'

services:
  
  db:
    image: mariadb:10.5.11
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: example
        MARIADB_DATABASE: booking
        MARIADB_USER: booking
        MARIADB_PASSWORD: booking

  adminer:
    image: adminer:4
    restart: unless-stopped
    ports:
      - 8080:8080
    links:
      - db